services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - TZ=America/New_York
      - DISPLAY=:1
      - VNC_PUBLIC_HOST=${VNC_PUBLIC_HOST:-localhost}  # For production
    env_file:
      - ./backend/.env
    depends_on:
      vnc:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - screenshots:/app/screenshots
      - uploads:/app/uploads
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - automation-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - TZ=America/New_York
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    command: npm run dev
    networks:
      - automation-network

  vnc:
    build: ./vnc
    ports:
      - "5901:5901"  # VNC
      - "7900:7900"  # noVNC HTTP with websockify
    environment:
      - DISPLAY=:1
      - TZ=America/New_York
    shm_size: '2gb'
    volumes:
      - screenshots:/app/screenshots
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5901"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - automation-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=automation
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - TZ=America/New_York
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d automation"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - automation-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - automation-network

networks:
  automation-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  screenshots:
  uploads:
