version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: automation-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
      - MINIO_DEFAULT_BUCKETS=automation-files
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - automation-network

  app:
    container_name: auto-flow-app-tigervnc
    build:
      context: .
      dockerfile: Dockerfile.tigervnc
    ports:
      - "8000:8000"            # Backend API
      - "8001:8001"            # Session Manager API
      - "5901-6000:5901-6000"  # VNC ports (TigerVNC)
      - "7901-8000:7901-8000"  # noVNC web ports
    env_file:
      - ./backend/.env
    environment:
      # Existing envs
      - VNC_PUBLIC_HOST=${VNC_PUBLIC_HOST:-localhost}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_BUCKET_NAME=automation-files
      - MINIO_PUBLIC_ENDPOINT=${MINIO_PUBLIC_ENDPOINT:-localhost:9000}
      - MINIO_REGION=us-east-1
      - STORAGE_BACKEND=minio
      # Multi-session flags
      - ENABLE_MULTI_SESSION=true
      - SESSION_MANAGER_URL=http://localhost:8001
      - MAX_SESSIONS=100
      - SESSION_TIMEOUT=30
      # Host capacity estimates (adjust to your host)
      - HOST_CPU_CORES=64
      - HOST_MEMORY_MB=131072
      - HOST_BANDWIDTH_Mbps=1000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - screenshots:/app/screenshots
      - uploads:/app/uploads
    shm_size: "2gb"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000 && nc -z localhost 8001"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - automation-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - TZ=America/New_York
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      app:
        condition: service_healthy
    command: npm run dev
    networks:
      - automation-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=automation
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - TZ=America/New_York
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d automation"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - automation-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - automation-network

networks:
  automation-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  screenshots:
  uploads:
  minio_data:
